spring:
   datasource:
      name: sicredi
      url: jdbc:h2:mem:slc;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      username: sa
      password: 
   jpa: 
      properties.hibernate.ddl-auto: create
      database-platform: org.hibernate.dialect.H2Dialect

server.port: 80